version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./backend:/app
      - /tmp/nautscan/capture.pcap:/app/capture.pcap
    environment:
      - DATABASE_URL=postgresql+asyncpg://nautscan:nautscan@postgres:5432/nautscan
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=nautscan
      - PORT=8001
      - HOST_CAPTURE_FILE=/app/capture.pcap
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    depends_on:
      - postgres
      - neo4j
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "3003:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001/api
    depends_on:
      - backend
    networks:
      - default

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=nautscan
      - POSTGRES_PASSWORD=nautscan
      - POSTGRES_DB=nautscan
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/nautscan
    volumes:
      - neo4j_data:/data
    networks:
      - default

volumes:
  postgres_data:
  neo4j_data:
